export const types = {
    //Sync
    AUTHENTICATE: 'AUTHENTICATE',
    INITIALIZE:   'INITIALIZE',

    //Async
    LOGIN_ASYNC:        'LOGIN_ASYNC',
    SIGNUP_ASYNC:       'SIGNUP_ASYNC',
    AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
    INITIALIZE_ASYNC:   'INITIALIZE_ASYNC',
};
